name: Publish Node.js Package
on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    if: ${{ contains(github.event.head_commit.message, '[publish]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/
      - name: publish npm
        run: |
          npm version patch
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
